# -*- coding: utf-8 -*-
"""Data Analysis BrewBridge Cafe.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10cHCKZjnTjzXPtuAois3ekEiayybp2zp

***Importing Data***
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

orders = pd.read_csv("Order_Information.csv")
menu = pd.read_csv("Menu_Information.csv")
campaign = pd.read_csv("Loyalty_Campaign_Information.csv")
customers = pd.read_csv("Customer_Information.csv")

orders.head()

orders.info()

orders.describe()

# Check Missing Values
 orders.isnull().sum()

# Check Duplicates
orders.duplicated().sum()

"""**Boxplots**"""

# Unit Price Boxplot
plt.figure(figsize=(6,4))
plt.boxplot(orders['Unit_Price_INR'])
plt.title("Boxplot of Unit Price")
plt.show()

# Quantity Ordered Boxplot
plt.figure(figsize=(6,4))
plt.boxplot(orders['Quantity'])
plt.title("Boxplot of Quantity Ordered")
plt.show()

# Total Amount Boxplot
import matplotlib.pyplot as plt
import pandas as pd

orders['Total_Amount_INR'] = pd.to_numeric(
    orders['Total_Amount_INR'],
    errors='coerce'
)

plt.figure(figsize=(6,4))

plt.boxplot(orders['Total_Amount_INR'].dropna())

plt.title("Boxplot of Total Amount")

plt.show()

# Customer Rating Boxplot
plt.figure(figsize=(6,4))
plt.boxplot(orders['Customer_Rating'].dropna())
plt.title("Boxplot of Customer Rating")
plt.show()

"""**Outlier Detection**"""

# Find Outliers Using IQR
Q1 = orders['Total_Amount_INR'].quantile(0.25)
Q3 = orders['Total_Amount_INR'].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

outliers = orders[
    (orders['Total_Amount_INR'] < lower) |
    (orders['Total_Amount_INR'] > upper)
]

outliers

"""**Correlation Analysis**"""

# Select Numeric Columns
numeric_cols = orders.select_dtypes(include=np.number)

# Correlation Matrix
corr = numeric_cols.corr()
corr

# Heatmap
import matplotlib.pyplot as plt

plt.figure(figsize=(8,6))
plt.imshow(corr)

plt.xticks(range(len(corr.columns)), corr.columns, rotation=90)
plt.yticks(range(len(corr.columns)), corr.columns)

plt.colorbar()
plt.title("Correlation Heatmap")

plt.show()

"""**Scatter Plots**"""

# Discount vs Total Amount
plt.figure(figsize=(6,4))

plt.scatter(
    orders['Discount_Amount_INR'],
    orders['Total_Amount_INR']
)

plt.xlabel("Discount Applied")
plt.ylabel("Total Amount")
plt.title("Discount vs Total Amount")

plt.show()

# Quantity vs Unit Price
plt.figure(figsize=(6,4))

plt.scatter(
    orders['Quantity'],
    orders['Unit_Price_INR']
)

plt.xlabel("Quantity")
plt.ylabel("Unit Price")
plt.title("Quantity vs Unit Price")

plt.show()

"""**Sales Visualizations**"""

# Revenue by Order Type
revenue_by_type = orders.groupby('Order_Type')['Total_Amount_INR'].sum()

revenue_by_type.plot(kind='bar')

plt.title("Revenue by Order Type")
plt.ylabel("Revenue")

plt.show()

# Revenue By category Bar Chart
revenue_by_category = orders.groupby('Category')['Total_Amount_INR'].sum()

revenue_by_category.plot(kind='bar')

plt.title("Revenue by Category")
plt.ylabel("Revenue")

plt.show()

# Histogram Of Discount Amounts
plt.figure(figsize=(6,4))

plt.hist(orders['Discount_Amount_INR'], bins=10)

plt.title("Histogram of Discount Amounts")
plt.xlabel("Discount Amount")
plt.ylabel("Frequency")

plt.show()

# Discount % Distribution Chart
discount_percentages = (orders['Discount_Amount_INR'] / orders['Total_Amount_INR']) * 100

discount_percentages.plot(kind='hist', bins=10)

plt.title("Discount % Distribution")
plt.xlabel("Discount %")
plt.ylabel("Frequency")

plt.show()

# Reward offer revenue conparision bar chart
reward_offer_revenue = orders.groupby('Reward_Applied')['Total_Amount_INR'].sum()

reward_offer_revenue.plot(kind='bar')

plt.title("Reward Offer Revenue Comparison")
plt.ylabel("Revenue")

plt.show()

# Payment Method Pie Chart
payment_method_counts = orders['Payment_Method'].value_counts()

payment_method_counts.plot(kind='pie', autopct='%1.1f%%')

plt.title("Payment Method Breakdown")
plt.xlabel("Payment Method")
plt.ylabel("Number of Orders")

plt.show()

# Customer Distribution By Region
customer_counts = customers['Region'].value_counts()

customer_counts.plot(kind='pie',autopct='%1.1f%%' )

plt.title("Customer Distribution by Region")
plt.ylabel("Number of Customers")

plt.show()